### PR TITLE
Update GNOME runtime to 42

### PR DESCRIPTION
**Pull request by sukahiroaki**
Title says it all.

### CODE REVIEW

**Comment by pcercuei** [comment]
It fails to build here, when building libfolks:
```
========================================================================
Building module folks in /tmp/org.gnome.Geary/.flatpak-builder/build/folks-1
========================================================================
The Meson build system
Version: 0.59.4
Source dir: /run/build/folks
Build dir: /run/build/folks/_flatpak_build
Build type: native build
Project name: folks
Project version: 0.15.3
C compiler for the host machine: ccache cc (gcc 11.3.0 "cc (GCC) 11.3.0")
C linker for the host machine: cc ld.bfd 2.37
Vala compiler for the host machine: valac (valac 0.56.1)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency gee-0.8 found: YES 0.20.5
Run-time dependency gio-2.0 found: YES 2.72.2
Run-time dependency glib-2.0 found: YES 2.72.2
Run-time dependency gmodule-2.0 found: YES 2.72.2
Run-time dependency gobject-2.0 found: YES 2.72.2
Library m found: YES
Library posix found: YES
Program g-ir-compiler found: YES (/usr/bin/g-ir-compiler)
Run-time dependency libebook-1.2 found: YES 3.40.4
Run-time dependency libebook-contacts-1.2 found: YES 3.40.4
Run-time dependency libedataserver-1.2 found: YES 3.40.4
Run-time dependency libxml-2.0 found: YES 2.9.12
Run-time dependency evolution-data-server-1.2 found: YES 3.40.4
Message: Building E-D-S with Sources service "org.gnome.evolution.dataserver.Sources5" AddressBook service "org.gnome.evolution.dataserver.AddressBook10"
Dependency libebook-1.2 found: YES 3.40.4 (cached)
Configuring config.h using configuration
Library build-conf found: YES
Program meson_post_install.py found: YES (/usr/bin/python3 /run/build/folks/meson_post_install.py)
Library folks-generics found: YES
Configuring org.freedesktop.folks.gschema.xml using configuration
Compiler for C supports link arguments -Wl,--version-script,/run/build/folks/backends/dummy/lib/folks-dummy.map: YES 
Configuring namespace.vala using configuration
Compiler for C supports link arguments -Wl,--version-script,/run/build/folks/backends/eds/lib/folks-eds.map: YES 
Library folks-test-dbus found: YES
Program manager-file.py found: YES (/run/build/folks/tests/tools/manager-file.py)
Build targets in project: 51

Found ninja-1.11.0 at /usr/bin/ninja
[3/204] Compiling Vala source ../folks/abstract-field-details.vala ../folks/alias-details.vala ../folks/..../folks/url-details.vala ../folks/utils.vala ../folks/web-service-details.vala folks/folks-internal.vapi
FAILED: folks/libfolks.so.26.0.0.p/abstract-field-details.c folks/libfolks.so.26.0.0.p/alias-details.c folks/libfolks.so.26.0.0.p/anti-linkable.c folks/libfolks.so.26.0.0.p/avatar-cache.c folks/libfolks.so.26.0.0.p/avatar-details.c folks/libfolks.so.26.0.0.p/backend-store.c folks/libfolks.so.26.0.0.p/backend.c folks/libfolks.so.26.0.0.p/birthday-details.c folks/libfolks.so.26.0.0.p/debug.c folks/libfolks.so.26.0.0.p/email-details.c folks/libfolks.so.26.0.0.p/extended-info.c folks/libfolks.so.26.0.0.p/favourite-details.c folks/libfolks.so.26.0.0.p/folks-namespace.c folks/libfolks.so.26.0.0.p/gender-details.c folks/libfolks.so.26.0.0.p/group-details.c folks/libfolks.so.26.0.0.p/im-details.c folks/libfolks.so.26.0.0.p/individual-aggregator.c folks/libfolks.so.26.0.0.p/individual.c folks/libfolks.so.26.0.0.p/interaction-details.c folks/libfolks.so.26.0.0.p/local-id-details.c folks/libfolks.so.26.0.0.p/location-details.c folks/libfolks.so.26.0.0.p/name-details.c folks/libfolks.so.26.0.0.p/note-details.c folks/libfolks.so.26.0.0.p/object-cache.c folks/libfolks.so.26.0.0.p/persona-store.c folks/libfolks.so.26.0.0.p/persona.c folks/libfolks.so.26.0.0.p/phone-details.c folks/libfolks.so.26.0.0.p/postal-address-details.c folks/libfolks.so.26.0.0.p/potential-match.c folks/libfolks.so.26.0.0.p/presence-details.c folks/libfolks.so.26.0.0.p/query.c folks/libfolks.so.26.0.0.p/role-details.c folks/libfolks.so.26.0.0.p/search-view.c folks/libfolks.so.26.0.0.p/simple-query.c folks/libfolks.so.26.0.0.p/types.c folks/libfolks.so.26.0.0.p/url-details.c folks/libfolks.so.26.0.0.p/utils.c folks/libfolks.so.26.0.0.p/web-service-details.c folks/folks/folks.h folks/folks.vapi folks/Folks-0.7.gir 
valac -C --debug --debug --vapidir /run/build/folks/folks -D FOLKS_COMPILATION /run/build/folks/folks/folks-generics.vapi /run/build/folks/folks/build-conf.vapi --pkg gee-0.8 --pkg gio-2.0 --pkg gmodule-2.0 --pkg gobject-2.0 --color=always --directory folks/libfolks.so.26.0.0.p --basedir ../folks --library folks --header folks/folks/folks.h --vapi ../folks.vapi --gir ../Folks-0.7.gir --includedir folks ../folks/abstract-field-details.vala ../folks/alias-details.vala ../folks/anti-linkable.vala ../folks/avatar-cache.vala ../folks/avatar-details.vala ../folks/backend-store.vala ../folks/backend.vala ../folks/birthday-details.vala ../folks/debug.vala ../folks/email-details.vala ../folks/extended-info.vala ../folks/favourite-details.vala ../folks/folks-namespace.vala ../folks/gender-details.vala ../folks/group-details.vala ../folks/im-details.vala ../folks/individual-aggregator.vala ../folks/individual.vala ../folks/interaction-details.vala ../folks/local-id-details.vala ../folks/location-details.vala ../folks/name-details.vala ../folks/note-details.vala ../folks/object-cache.vala ../folks/persona-store.vala ../folks/persona.vala ../folks/phone-details.vala ../folks/postal-address-details.vala ../folks/potential-match.vala ../folks/presence-details.vala ../folks/query.vala ../folks/role-details.vala ../folks/search-view.vala ../folks/simple-query.vala ../folks/types.vala ../folks/url-details.vala ../folks/utils.vala ../folks/web-service-details.vala folks/folks-internal.vapi
/run/build/folks/folks/folks-generics.vapi:40.30-40.30: error: The type name `G' could not be found
   40 |     internal static SmallSet<G> copy (Gee.Iterable<G> iterable,
      |                              ^                                 
/run/build/folks/folks/folks-generics.vapi:40.52-40.52: error: The type name `G' could not be found
   40 |     internal static SmallSet<G> copy (Gee.Iterable<G> iterable,
      |                                                    ^           
/run/build/folks/folks/folks-generics.vapi:41.32-41.32: error: The type name `G' could not be found
   41 |         owned Gee.HashDataFunc<G>? item_hash = null,
      |                                ^                    
/run/build/folks/folks/folks-generics.vapi:42.33-42.33: error: The type name `G' could not be found
   42 |         owned Gee.EqualDataFunc<G>? item_equals = null);
      |                                 ^                       
../folks/backend-store.vala:765.45-765.66: warning: `GLib.ModuleFlags.BIND_LOCAL' has been deprecated since vala-0.46. Use LOCAL
  765 |       var _module = Module.open (file_path, ModuleFlags.BIND_LOCAL);
      |                                             ^~~~~~~~~~~~~~~~~~~~~~  
Compilation failed: 4 error(s), 1 warning(s)
[4/204] Compiling C object folks/libfolks-internal.a.p/small-set.c.o
ninja: build stopped: subcommand failed.
```

**Comment by bellegarde-c** [comment]
It works now, see #55

**Comment by pcercuei** [comment]
@bellegarde-c please re-read my previous message.

**Comment by bellegarde-c** [comment]
@pcercuei Here it works (flatpak build) and even if I'm building gnumdk/stable branch (Geary stable with backports), I'm sure I do not have fixed errors present in previous message.

**Comment by pcercuei** [comment]
@bellegarde-c but did you bump the GNOME runtime to 42?

**Comment by bellegarde-c** [comment]
Below the manifest I used

```
---
# Flatpak builder manifest for Geary.
#
# When updating this file after branching a new stable release, the
# following should be updated:
#
# - app branch and geary source branches
# - remove app tags and desktop-file-name-prefix
#
# When updating the Flathub manifest, copy the stable manifest over it
# and pin each source to a specific tarball.
#

app-id: org.gnome.Geary
branch: stable
runtime: org.gnome.Platform
runtime-version: "42"
sdk: org.gnome.Sdk
command: geary

finish-args:
  # X11 + XShm access
  - "--share=ipc"
  - "--socket=fallback-x11"

  # Wayland access
  - "--socket=wayland"

  # OpenGL access for WK2
  - "--device=dri"

  # Sent mail sound plugin
  - "--socket=pulseaudio"

  # Needs to talk to the network
  - "--share=network"

  # Secrets access
  - "--talk-name=org.freedesktop.secrets"

  # Contacts open/edit support
  - "--talk-name=org.gnome.Contacts"

  # GOA support
  - "--talk-name=org.gnome.ControlCenter"
  - "--talk-name=org.gnome.OnlineAccounts"

  # Folks contact and avatar support (via EDS)
  - "--talk-name=org.gnome.evolution.dataserver.*"
  - "--filesystem=xdg-cache/evolution/addressbook:ro"

  # Migrate GSettings into the sandbox
  - "--metadata=X-DConf=migrate-path=/org/gnome/Geary/"

  # Migrate Geary settings from other release versions
  - "--filesystem=~/.config/geary:ro"

  # Workaround for printing to PDF until WebKitGTK supports printing
  - "--filesystem=xdg-download:rw"

  # Let view source keep on working as-sis for now. Bug 779311.
  - "--filesystem=/tmp"

cleanup:
  - /include
  - /lib/pkgconfig
  - /man
  - /share/aclocal
  - /share/gir-1.0
  - /share/girepository-1
  - /share/gtk-doc
  - /share/man
  - /share/pkgconfig
  - /share/vala
  - "*.la"
  - "*.a"

modules:

  # Geary dependency
  - name: gnome-online-accounts
    config-opts:
      - "--disable-telepathy"
      - "--disable-documentation"
      - "--disable-backend"
      # Enabling debug via configure causes both -g and -O0 # to be
      # set, which is bad since the former is redundant with the
      # default fd.o build-options, and the latter conflicts with
      # them. So disable debug instead.
      - "--enable-debug=no"
    sources:
      - type: archive
        url: https://download.gnome.org/sources/gnome-online-accounts/3.40/gnome-online-accounts-3.40.0.tar.xz
        sha256: 585c4f979f6f543b77bfdb4fb01eb18ba25c2aec5b7866c676d929616fb2c3fa

  # Geary dependency
  - name: gspell
    config-opts:
      - "--disable-gtk-doc"
      - "--disable-gtk-doc-html"
    sources:
      - type: archive
        url: https://download.gnome.org/sources/gspell/1.9/gspell-1.9.1.tar.xz
        sha256: dcbb769dfdde8e3c0a8ed3102ce7e661abbf7ddf85df08b29915e92cd723abdd
    cleanup:
      - /bin
      - /share

  # EDS dependency
  - name: libical
    buildsystem: cmake-ninja
    config-opts:
      - "-DBUILD_SHARED_LIBS:BOOL=ON"
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DCMAKE_INSTALL_LIBDIR=lib"
      - "-DGOBJECT_INTROSPECTION=true"
      - "-DICAL_BUILD_DOCS=false"
      - "-DICAL_GLIB=true"
      - "-DICAL_GLIB_VAPI=true"
    sources:
      - type: archive
        url: https://github.com/libical/libical/releases/download/v3.0.11/libical-3.0.11.tar.gz
        sha256: 1e6c5e10c5a48f7a40c68958055f0e2759d9ab3563aca17273fe35a5df7dbbf1
    cleanup:
      - /lib/cmake

  # EDS and sound-theme-freedesktop dependency
  - shared-modules/intltool/intltool-0.51.json

  # Geary dependency
  - name: evolution-data-server
    buildsystem: cmake-ninja
    config-opts:
      - "-DCMAKE_BUILD_TYPE=Release"
      - "-DENABLE_CANBERRA=OFF"
      - "-DENABLE_EXAMPLES=OFF"
      - "-DENABLE_GOA=ON"
      - "-DENABLE_GOOGLE=OFF"
      - "-DENABLE_GTK=ON"
      - "-DENABLE_GTK_DOC=OFF"
      - "-DENABLE_INSTALLED_TESTS=OFF"
      - "-DENABLE_INTROSPECTION=ON"
      - "-DENABLE_VALA_BINDINGS=ON"
      - "-DENABLE_WEATHER=OFF"
      - "-DWITH_LIBDB=OFF"
      - "-DWITH_OPENLDAP=OFF"
    sources:
      - type: archive
        url: https://download.gnome.org/sources/evolution-data-server/3.40/evolution-data-server-3.40.4.tar.xz
        sha256: 87c185f18c37270e3611981f19bd9221ac974c807462c8dce90bea08712c5800
    cleanup:
      - /lib/cmake
      - /lib/evolution-data-server/*-backends
      - /libexec
      - /share/dbus-1/services

  # Geary dependency
  - name: folks
    buildsystem: meson
    config-opts:
      - "-Dtelepathy_backend=false"
      - "-Dbluez_backend=false"
      - "-Dinspect_tool=false"
      - "-Dimport_tool=false"
    sources:
      - type: archive
        url: https://download.gnome.org/sources/folks/0.15/folks-0.15.5.tar.xz
        sha256: 0fff8a896330cd82aee4598324f7e541c884d0337536212723b4beb38c759086
    cleanup:
      - /bin

  # GSound dependency
  - shared-modules/libcanberra/libcanberra.json

  # Geary dependency, workaround libsecret access via secret portal
  # being non-functional GNOME/libsecret#58
  - name: libsecret
    sources:
      - type: archive
        url: https://download.gnome.org/sources/libsecret/0.19/libsecret-0.19.1.tar.xz
        sha256: 8583e10179456ae2c83075d95455f156dc08db6278b32bf4bd61819335a30e3a

  # Geary dependency
  - name: gsound
    buildsystem: meson
    sources:
      - type: archive
        url: https://download.gnome.org/sources/gsound/1.0/gsound-1.0.3.tar.xz
        sha256: ca2d039e1ebd148647017a7f548862350bc9af01986d39f10cfdc8e95f07881a

  # Geary dependency
  - name: gmime
    sources:
      - type: archive
        url: https://github.com/jstedfast/gmime/archive/3.2.7.tar.gz
        sha256: 442db212b9ad71a13397b54cea742ab27cfcf95f43b3eb3d7ac4cec7cb4e59e5

  # Geary dependency
  - name: libpeas
    buildsystem: meson
    sources:
      - type: archive
        url: https://download.gnome.org/sources/libpeas/1.30/libpeas-1.30.0.tar.xz
        sha256: 0bf5562e9bfc0382a9dcb81f64340787542568762a3a367d9d90f6185898b9a3

  # Geary dependency
  - name: "libytnef"
    sources:
      - type: archive
        url: https://github.com/Yeraze/ytnef/archive/v2.0.tar.gz
        sha256: bb12f34572de89e4825fce98d2d235d93cd34b2c41fed0074ebfa89af9e724a9

  # Geary dependency
  - name: snowball
    buildsystem: simple
    sources:
      - type: archive
        url: https://github.com/snowballstem/snowball/archive/refs/tags/v2.1.0.tar.gz
        sha512: 1efd7d8ab58852987e83247048244882c517e32237c8cb3c0558b66ecfb075733ce8805ebb76041e6e7d6664c236054effe66838e7c524ee529ce869aa8134f0
      - type: patch
        paths:
          - patches/snowball-shared-library.diff
    build-commands:
      - "make libstemmer.so -j$FLATPAK_BUILDER_N_JOBS"
      - "install -Dm644 include/libstemmer.h /app/include/libstemmer.h"
      - "install -Dm644 libstemmer.so.0.0.0 /app/lib/libstemmer.so.0.0.0"
      - "ln -s libstemmer.so.0.0.0 /app/lib/libstemmer.so.0"
      - "ln -s libstemmer.so.0 /app/lib/libstemmer.so"

  # Geary dependency
  - name: sound-theme-freedesktop
    sources:
      - type: archive
        url: http://people.freedesktop.org/~mccann/dist/sound-theme-freedesktop-0.8.tar.bz2
        sha256: cb518b20eef05ec2e82dda1fa89a292c1760dc023aba91b8aa69bafac85e8a14

  - name: geary
    buildsystem: meson
    config-opts:
      - "-Dprofile=release"
    sources:
      - type: git
        url: https://gitlab.gnome.org/GNOME/geary.git
        branch: "gnumdk/stable"

```

**Comment by pcercuei** [comment]
That works.

**Comment by fedelibre** [comment]
@sukahiroaki you can close it, as the update to 43 was merged a few days ago

**Comment by sukahiroaki** [comment]
See above, fixed in another commit. Closing.

**Pull request closed without merging**
